name: generate snake animation (new year edition)

on:
  schedule:
    - cron: "0 0 * * *" # запускается каждый день
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation (New Year Theme)
        uses: Platane/snk@v3
        with:
          github_user_name: mnasonovy
          outputs: dist/github-contribution-grid-snake-newyear.svg

          # Яркая новогодняя палитра
          color_snake: "#FF5555"          # красная змейка (как гирлянда/нос у оленя)
          color_dots: "#050814,#004400,#00FF00,#FF0000,#FFD700"
          #            пусто    низкая    средняя   высокая  макс активность
          color_empty: "#050814"          # почти чёрный зимний ночной фон
          color_path: "#FFD700"           # золотой след за змейкой
          color_border: "#FFD700"         # тонкая золотая рамка
          background: "#050814"           # тот же тёмный фон

      - name: Push generated Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
